version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: N@black08
      POSTGRES_DB: detectdb
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://srikanthnaidu04:N%40black08@db:5432/detectdb"

volumes:
  db-data:
